### ISSUE TITLE
Error on startup, either from the Banner or Boat pull 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Humbug#45]
2015-05-18 22:37:00 [ERROR] Could not load 'plugins/Humbug-1.6.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/MinecraftKey
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-5818108-db5fd9c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-5818108-db5fd9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-5818108-db5fd9c]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/MinecraftKey
        at com.untamedears.humbug.Humbug.<clinit>(Humbug.java:2170) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45-internal]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.MinecraftKey
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45-internal]
        at com.untamedears.humbug.Humbug.<clinit>(Humbug.java:2170) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45-internal]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-5818108-db5fd9c]
        ... 6 more

**Comment by BlackXnt** [comment]
I am pretty sure this error has nothing to do with the banners on the boats. It's the ender pearl thing again. Did you grab this build - http://civcraft.co:8080/view/Development/job/Humbug-dev/17/ ? I installed it on my testing server and I don't get this error and the boat fix is on it.

**Comment by rourke750** [comment]
Um are you using spigot 1.8.4?

**Comment by BlackXnt** [comment]
No 1.8.3

**Comment by rourke750** [comment]
> v1_8_R3

Means he is using a different version to 1.8.3.  1.8.3 is v1_8_R2  which is what the code is looking for.

**Comment by BlackXnt** [comment]
So the update civtest to 1.8.4 is the problem?

**Comment by rourke750** [comment]
Yes

**Comment by ttk2** [comment]
should I just roll back or do you want to compile forward?
